### ISSUE TITLE
Failed to activate the markdown-toc package

### ISSUE THREAD

**Issue by jhbush** [nok/markdown-toc#39]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [markdown-toc](https://github.com/voidplus/markdown-toc) package, v0.2.1

### Stack Trace

Failed to activate the markdown-toc package

```
At Cannot read property 'insertText' of undefined

TypeError: Cannot read property 'insertText' of undefined
    at Toc.module.exports.Toc.create (/Users/jbush/.atom/packages/markdown-toc/lib/Toc.coffee:33:25)
    at new Toc (/Users/jbush/.atom/packages/markdown-toc/lib/Toc.coffee:16:12)
    at Object.module.exports.activate (/Users/jbush/.atom/packages/markdown-toc/lib/markdown-toc.coffee:8:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
```

### Commands

```
     -0:00.5.0 markdown-toc:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
markdown-toc, v0.2.1

# Dev
No dev packages
```

**Comment by nok** [comment]
Thank you @jhbush ,

could you please update the package and test it again.

Happy coding,
Darius

**Comment by jhbush** [comment]
Hey sorry for the late reply but everything is working as expected. Thanks for fixing the issue.

**Comment by nok** [comment]
@jhbush, thank you for responding. :+1:
