### ISSUE TITLE
Failed to activate the markdown-toc package 

### ISSUE THREAD

**Issue by v4Corg** [nok/markdown-toc#78]
[Enter steps to reproduce below:]

1. simply happens every time i try Packages->markdown-toc->Toggle

**Atom Version**: 1.9.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: [markdown-toc](https://github.com/nok/markdown-toc) package, v0.4.1

### Stack Trace

Failed to activate the markdown-toc package

```
At this.editor.getBuffer is not a function

TypeError: this.editor.getBuffer is not a function
    at Toc.module.exports.Toc.___updateLines (file:///C:/Users/admin/.atom/packages/markdown-toc/lib/Toc.coffee:188:24)
    at Toc.module.exports.Toc._hasToc (file:///C:/Users/admin/.atom/packages/markdown-toc/lib/Toc.coffee:59:6)
    at Toc.module.exports.Toc.create (file:///C:/Users/admin/.atom/packages/markdown-toc/lib/Toc.coffee:29:9)
    at new Toc (file:///C:/Users/admin/.atom/packages/markdown-toc/lib/Toc.coffee:14:6)
    at Object.module.exports.activate (file:///C:/Users/admin/.atom/packages/markdown-toc/lib/markdown-toc.coffee:6:16)
    at Package.module.exports.Package.activateNow (C:\Users\admin\AppData\Local\atom\app-1.9.8\resources\app.asar\src\package.js:183:20)
    at C:\Users\admin\AppData\Local\atom\app-1.9.8\resources\app.asar\src\package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\admin\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\admin\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\admin\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (C:\Users\admin\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\admin\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\admin\AppData\Local\atom\app-1.9.8\resources\app.asar\src\atom-environment.js:1104:28)
    at EventEmitter.outerCallback (C:\Users\admin\AppData\Local\atom\app-1.9.8\resources\app.asar\src\application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

### Commands

```
     -4:57 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -4:56.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -4:54.8.0 core:delete (atom-text-editor.editor.is-focused)
     -4:54.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:53.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:52.9.0 core:select-down (atom-text-editor.editor.is-focused)
     -4:52.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:22.4.0 markdown-mindmap:toggle (atom-text-editor.editor.is-focused)
  6x -2:58.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:57.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:48 markdown-toc:toggle (atom-text-editor.editor.is-focused)
     -0:30.7.0 dev-live-reload:reload-all (atom-text-editor.editor.is-focused)
     -0:27.7.0 markdown-toc:toggle (atom-text-editor.editor.is-focused)
     -0:21.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:19.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 markdown-toc:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
markdown-mindmap, v0.2.4 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-toc, v0.4.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (active)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by twolsten** [comment]
Any update on this?  I am getting the same error

**Comment by ghost** [comment]
Any progress here?

**Comment by jehovahmidara** [comment]
Any progress on how this issue can be rectified..

**Comment by joshuadanpeterson** [comment]
[Enter steps to reproduce:]

1. Same issue as above.
2. My guess is that I downloaded another package w/in the last 24 hrs that's interfering w/it, but currently not sure.

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [markdown-toc](https://github.com/nok/markdown-toc) package 0.4.2


### Stack Trace

Failed to activate the markdown-toc package

```
At line.match is not a function

TypeError: line.match is not a function
    at Toc.module.exports.Toc._hasToc (/packages/markdown-toc/lib/Toc.coffee:69:19)
    at Toc.module.exports.Toc.create (/packages/markdown-toc/lib/Toc.coffee:29:9)
    at /packages/markdown-toc/lib/Toc.coffee:14:6)
    at Object.activate (/packages/markdown-toc/lib/markdown-toc.coffee:6:12)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3212282)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.o (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1879)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1212922)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214363)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348922)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347765)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:723427)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:731350)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -2:53.9.0 markdown-writer:insert-new-line (input.hidden-input)
     -2:53.5.0 editor:newline (input.hidden-input)
     -2:53.4.0 markdown-writer:insert-new-line (input.hidden-input)
     -2:53.4.0 editor:newline (input.hidden-input)
     -2:42.4.0 fonts:open-font-selector (ul.list-inline.tab-bar.inset-panel)
  3x -1:15 window:increase-font-size (input.hidden-input)
     -1:07.1.0 core:save (input.hidden-input)
  2x -1:02.8.0 markdown-writer:insert-new-line (input.hidden-input)
  3x -1:00.9.0 core:backspace (input.hidden-input)
  2x -0:59.1.0 core:move-up (input.hidden-input)
     -0:54.4.0 core:save (input.hidden-input)
     -0:51.2.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:51.2.0 editor:newline (input.hidden-input)
     -0:51.1.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:51.1.0 editor:newline (input.hidden-input)
     -0:41.1.0 markdown-toc:toggle (input.hidden-input)
```

### Non-Core Packages

```
ABC-notation 1.0.1 
ascii-art 1.2.0 
ascii-hex 0.2.0 
ascii-tree 1.1.0 
ask-stack 2.2.0 
atom-abc-editor 1.1.0 
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-ghost 0.1.0 
atom-github-issues 0.4.3 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-medium 2.0.1 
atom-notes 1.20.2 
atom-python-virtualenv 1.0.4 
atom-shortcuts 0.0.2 
atom-terminal 0.8.0 
atom-ternjs 0.20.0 
atom-visual-studio-code-ui 2.1.0 
atom-vlc 0.2.2 
autocomplete 0.47.0 
autocomplete-ascii-emoji 1.0.0 
autocomplete-bibtex 1.2.7 
autocomplete-emojis 2.5.0 
autocomplete-en-en 0.2.0 
autocomplete-google-suggest 1.1.0 
autocomplete-python 1.16.0 
autocorrect-en 0.0.3 
busy-signal 2.0.1 
code-dictation 0.0.13 
date 2.6.0 
delete-lines 0.5.0 
diagrams 0.30.0 
dictionary 0.5.0 
document-outline 2.1.2 
file-icons 2.1.38 
fonts 3.10.0 
fountain 0.8.3 
foxdot 1.0.0 
gfm-pdf 0.3.5 
ginger 0.1.1 
gist 1.1.0 
gist-it 0.9.2 
github-search 0.1.0 
glist 2.2.0 
googlesearch 1.5.0 
graphviz-preview-plus 1.5.10 
gtk-dark-theme 0.1.4 
Hydrogen 2.13.1 
imdone-atom 2.4.33 
imdone-atom-github 0.1.11 
intentions 1.1.5 
jekyll-syntax-highlighting 0.1.0 
kite 0.176.0 
language-alda 0.5.0 
language-applescript 0.3.0 
language-atom-notes 0.4.1 
language-autotools 2.0.1 
language-chmusick 1.2.0 
language-chordpro 0.2.5 
language-csound 0.3.5 
language-dot 1.7.0 
language-javascript-jxa 0.2.9 
language-markdown 0.37.0 
language-mediawiki 2.2.0 
language-pfm 0.82.0 
language-plantuml 0.2.0 
language-todotxt 1.1.5 
language-vba 0.2.5 
language-vbscript 0.9.0 
languagetool 0.1.1 
linter 2.3.1 
linter-flake8 2.4.0 
linter-languagetool 0.9.0 
linter-markdown 5.2.11 
linter-proselint 3.3.0 
linter-ui-default 1.8.1 
markdown-fold 0.3.0 
markdown-mindmap 0.6.2 
markdown-pdf 2.2.0 
markdown-preview-plus 3.11.5 
markdown-toc 0.4.2 
markdown-writer 2.11.9 
minimap 4.29.9 
multi-cursor 3.0.0 
musa-dsl-atom-repl 0.1.4 
my-ascii-art 0.1.0 
my-github-profile 0.2.1 
notes-from-pdf 0.4.2 
open-html-in-browser 0.2.1 
pandoc 0.2.2 
pdf-view 0.72.0 
pen-paper-coffee-syntax 0.17.0 
plantuml-preview 0.12.10 
platformio-ide-terminal 2.10.0 
predawn-syntax 1.0.4 
pretty-json 2.1.2 
preview-inline 1.5.1 
processing 0.13.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
python-autopep8 0.1.3 
remote-ftp 2.2.4 
rhyming-dictionary 0.3.2 
rst-preview-pandoc 0.1.12 
script 3.25.0 
scroll-through-time 0.3.1 
set-syntax 0.4.0 
shortcuts-teacher 0.0.4 
slack-chat 3.4.2 
sync-sync 2.0.2 
tablr 1.8.3 
teacode-atom-helper 1.2.3 
teletype 0.13.4 
thesaurus 0.3.0 
tidy-markdown 3.0.1 
todo 0.6.0 
tool-bar 1.2.0 
tool-bar-markdown-writer 0.5.0 
wordcount 3.1.0 
zentabs 0.8.9 
zotero-citations 5.2.0 
```

**Comment by kay2thebee** [comment]
Same issue.

**Comment by OlivierCasse** [comment]
+1

**Comment by cbbrahm** [comment]
+1

**Comment by Shiva108** [comment]
+1
